Repository jscraftcamp/website, pull requests merged in 2019-06, with the labels that each got.

#643 Create stefan_sauterleute.json
  participants/stefan_sauterleute.json
Labels: [registration] more information requested

#642 Create max_langer.json
  participants/max_langer.json
Labels: [registration] more information requested

#622 feat: add ability to provide twitter handle
  participants/markus_tacker.json
  src/participants.ejs
  src/registration.ejs
  test/participants.js
Labels: enhancement, jscc19

#631 Create jonathan_häberle
  participants/jonathan_häberle.json
Labels: [registration] tests not passing

#650 Add dejan_ranisavljevic.json
  participants/dejan_ranisavljevic.json
Labels: [registration] more information requested

#664 Create michael_jaser.json
  participants/michael_jaser.json
Labels: [registration] check boxes not checked

#677 Register Sepehr Lajevardi.
  participants/sepehr_lajevardi.json
Labels: [registration] more information requested

#679 Added michael_hoffmann.json
  participants/michael_hoffmann.json
Labels: [registration] tests not passing

#702 Registration for Willy Schott
  participants/willy_schott.json
Labels: allows to be quoted
