Repository jscraftcamp/website, pull requests merged in 2019-07, with the labels that each got.

#719 Create julian_jaser.json
  participants/julian_jaser.json
Labels: [registration] tests not passing

#645 Create oren_aksakal.json
  participants/oren_aksakal.json
Labels: [registration] more information requested

#731 Add Tobias Gutmann to participants
  participants/tobias_gutmann.json
Labels: [registration] more information requested

#756 Add Oleksandr Fedotov to participants list
  participants/oleksandr_fedotov.json
  test/participants.js
Labels: [registration] more information requested

#762 register jonas_lorenz and daniel_glasemann
  participants/daniel_glasemann.json
  participants/jonas_lorenz.json
Labels: [registration] more information requested

#765 Checking in
  participants/martin_duerre.json
Labels: [registration] (other) action required

#767 please add feli - thank you
  participants/felicitas_kugland.jscon
Labels: [registration] check boxes not checked

#776 registration florian_seif v2
  participants/florian_seif.json
Labels: [registration] tests not passing

#789 Add hengrui_jiang and philipp_krenz
  participants/hengrui_jiang.json
  participants/philipp_krenz.json
Labels: [registration] more information requested
