Repository jscraftcamp/website, pull requests merged in 2022-06, with the labels that each got.

#1174 Create william_ma.json
  participants/william_ma.json
Labels: [registration] tests not passing

#1202 Register to JSCraftCamp
  participants/maksym_hopei.json
Labels: [registration] more information requested

#1222 Add sponsor for Saturday lunch
  src/sections/schedule/schedule.js
Labels: website, jscc22
