Repository jscraftcamp/website, pull requests merged in 2024-05, with the labels that each got.

#1975 Create basan_kuberlinov.json
  participants/basan_kuberlinov.json
Labels: [registration] tests not passing

#1981 Add participant Krishna Singh
  participants/krishnasingh.json
Labels: [registration] tests not passing

#2001 Add disclaimer for dietary requirements
  src/routes/registration/+page.svelte
Labels: website

#2002 Add pricing information - it is free
  src/routes/+page.svelte
Labels: website

#1960 adding berlinjunker
  participants/berlinjunker.json
Labels: [registration] more information requested

#2038 Add "Christopher Voit"as a participant
  participants/christopher_voit.json
Labels: [registration] tests not passing
