Repository jscraftcamp/website, pull requests merged in 2024-06, with the labels that each got.

#2053 chore: add dgrabla as participant
  participants/dgrabla.json
Labels: :hourglass_flowing_sand: waitlist-friday

#2063 Create $ruslana.json
  participants/$ruslana.json
Labels: :hourglass_flowing_sand: waitlist-friday, :hourglass_flowing_sand: waitlist-saturday

#2064 waitlist for kerstin_dengl
  participants/kerstin_dengl.json
Labels: :hourglass_flowing_sand: waitlist-friday

#2067 Create Aditya_Joshi.json
  participants/Aditya_Joshi.json
Labels: :hourglass_flowing_sand: waitlist-friday, :hourglass_flowing_sand: waitlist-saturday

#2077 add jan as participant
  participants/jan_wahler.json
Labels: [registration] check boxes not checked, :hourglass_flowing_sand: waitlist-friday, :hourglass_flowing_sand: waitlist-saturday

#2078 Add jgil participant
  participants/jgil.json
Labels: :hourglass_flowing_sand: waitlist-friday, :hourglass_flowing_sand: waitlist-saturday
