Repository jscraftcamp/website, pull requests merged in 2025-06, with the labels that each got.

#2223 Registration JS CraftCamp 2025
  participants/christian.json
Labels: [registration] (other) action required

#2231 added tobias oettl
  participants/tobias_oettl.json
Labels: sponsoring

#2227 Add kino-auge
  participants/kino-auge.json
Labels: [registration] tests not passing

#2198 feat: add Jacob Ayokunle as a participant
  participants/jacob.json
Labels: [registration] (other) action required

#2232 Create berat-dev.json
  participants/berat-dev.json
Labels: sponsoring

#2235 Jeff
  participants/jewgenijsteinhart.json
Labels: [registration] (other) action required

#2255 Hetzner sponsors 500,- (not 300,-)
  src/lib/sponsoring/Sponsors2025.svelte
Labels: website

#2234 Create bswebdes.json
  participants/bswebdes.json
Labels: [registration] (other) action required

#2273 update: Robert wants to attends on Friday
  participants/robert-hostlowsky.json
Labels: :hourglass_flowing_sand: waitlist-friday

#2243 Create max_hopei Friday & Sat
  participants/max_hopei.json
Labels: :hourglass_flowing_sand: waitlist-friday
